# Generated by Django 4.2 on 2024-02-07 04:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('store', '0002_alter_sale_sale_type'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.sale')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.melimituser')),
            ],
            options={
                'unique_together': {('user', 'sale')},
            },
        ),
    ]
