# Generated by Django 4.2 on 2024-02-06 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderhistory',
            name='amount',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='orderhistory',
            name='co2',
            field=models.IntegerField(),
        ),
    ]
