services:
  web:
    build: .
    container_name: django_gunicorn
    volumes:
      - ./src:/app
      - static_volume:/usr/share/nginx/html/static/  # 追加
    ports:
      - "8000:8000"
    depends_on:
      - db
      - nginx
  db:
    image: mysql:8.0.28
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: o-hara_db
      MYSQL_USER: admin
      MYSQL_PASSWORD: o-hara
    volumes:
      - db_data:/var/lib/mysql
  nginx:
    image: nginx:1.21.1
    container_name: nginx_server
    ports:
      - "80:80"
      - "443:443"  # SSL対応のために443ポートを追加
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - static_volume:/usr/share/nginx/html/static  # 追加
      - ${VOLUME_PATH}:/etc/nginx/ssl/fullchain.pem #追記
      - ${VOLUME_PATH2}:/etc/nginx/ssl/privkey.pem #追記
      # - /etc/letsencrypt/live/teama-sub.o-hara-oita.click/fullchain.pem:/etc/nginx/ssl/fullchain.pem #追記
      # - /etc/letsencrypt/live/teama-sub.o-hara-oita.click/privkey.pem:/etc/nginx/ssl/privkey.pem #追記
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:5.2.0
    container_name: phpmyadmin
    environment:
      PMA_HOST: teamaa-rds.czm4eswsq0yn.us-east-1.rds.amazonaws.com
      PMA_USER: admin
      PMA_PASSWORD: o-hara2023
      PMA_ARBITRARY: 1
      PMA_PORT: 3306
      # MYSQL_ROOT_PASSWORD: o-hara2023
    ports:
      - "8080:80"
    depends_on:
      - db

volumes:
  db_data:
  static_volume:  # 追加
