# Generated by Django 4.2 on 2023-11-30 01:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=200, verbose_name='商品名')),
                ('product_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='定価')),
                ('weight', models.IntegerField(verbose_name='重量')),
                ('product_image', models.ImageField(upload_to='images', verbose_name='商品画像')),
                ('product_category', models.CharField(blank=True, choices=[('meat', 'meat'), ('vegetables', 'vegetables'), ('fruit', 'fruit'), ('fish', 'fish')], max_length=20, verbose_name='カテゴリ')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.melimitstore', verbose_name='店舗名')),
            ],
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sale_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='販売価格')),
                ('sale_start', models.DateTimeField(verbose_name='販売開始日時')),
                ('sale_end', models.DateTimeField(verbose_name='販売終了日時')),
                ('stock', models.IntegerField(verbose_name='在庫数')),
                ('expiration_date', models.DateField(verbose_name='賞味期限')),
                ('description', models.TextField(verbose_name='商品の説明')),
                ('sale_type', models.CharField(blank=True, choices=[('general_sales', '一般商品'), ('melimit_sales', '共同販売商品')], max_length=20, verbose_name='販売タイプ')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.product')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.melimitstore')),
            ],
        ),
    ]
