# Generated by Django 4.2 on 2023-11-22 05:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0018_alter_melimituser_taste'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=200)),
                ('product_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('weight', models.IntegerField()),
                ('product_image', models.ImageField(upload_to='images')),
                ('product_category', models.CharField(blank=True, choices=[('meat', 'meat'), ('vegetables', 'vegetables'), ('fruit', 'fruit'), ('fish', 'fish')], max_length=20, verbose_name='カテゴリ')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.melimitstore')),
            ],
        ),
    ]
