# Generated by Django 4.2 on 2024-01-24 05:02

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ThresholdCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(verbose_name='個数')),
                ('price', models.IntegerField(verbose_name='金額')),
                ('order_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_threshold_clear', models.BooleanField(default=False)),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.sale')),
                ('threshold', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.threshold')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.melimitstore')),
            ],
        ),
    ]
