# Generated by Django 4.2 on 2024-02-06 00:42

import django.core.validators
from django.db import migrations, models
import store.models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_category',
            field=models.CharField(choices=[('meat', '肉類'), ('vegetables', '野菜'), ('fruit', '果物'), ('fish', '魚介類'), ('other', 'その他')], max_length=20, verbose_name='カテゴリ'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_image',
            field=models.ImageField(blank=True, upload_to='images', verbose_name='商品画像'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_name',
            field=models.CharField(max_length=30, verbose_name='商品名'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_price',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(1000000)], verbose_name='定価'),
        ),
        migrations.AlterField(
            model_name='product',
            name='weight',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10000)], verbose_name='重量'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='description',
            field=models.TextField(max_length=500, verbose_name='商品の説明'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='expiration_date',
            field=models.DateField(validators=[store.models.validate_date], verbose_name='賞味期限'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='sale_end',
            field=models.DateField(validators=[store.models.validate_date], verbose_name='販売終了日時'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='sale_price',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(1000000)], verbose_name='販売価格'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='sale_start',
            field=models.DateField(validators=[store.models.validate_date], verbose_name='販売開始日時'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='sale_type',
            field=models.CharField(choices=[('general_sales', '一般商品'), ('melimit_sales', '共同商品')], max_length=20, verbose_name='販売タイプ'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='stock',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10000)], verbose_name='在庫数'),
        ),
        migrations.AlterField(
            model_name='threshold',
            name='discount_rate',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(99)], verbose_name='割引率'),
        ),
        migrations.AlterField(
            model_name='threshold',
            name='threshold',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(1000)], verbose_name='しきい値'),
        ),
    ]
