# Generated by Django 4.2 on 2024-01-24 05:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('store', '0002_thresholdcheck'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thresholdcheck',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.melimituser'),
        ),
    ]
