# Generated by Django 4.2 on 2023-11-27 02:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_alter_melimituser_taste'),
        ('store', '0002_sale'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sale',
            name='actual_price',
        ),
        migrations.AlterField(
            model_name='product',
            name='product_image',
            field=models.ImageField(upload_to='images', verbose_name='商品画像'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_name',
            field=models.CharField(max_length=200, verbose_name='商品名'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='定価'),
        ),
        migrations.AlterField(
            model_name='product',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.melimitstore', verbose_name='店舗名'),
        ),
        migrations.AlterField(
            model_name='product',
            name='weight',
            field=models.IntegerField(verbose_name='重量'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='description',
            field=models.TextField(verbose_name='商品の説明'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='expiration_date',
            field=models.DateField(verbose_name='賞味期限'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='sale_end',
            field=models.DateTimeField(verbose_name='販売終了日時'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='sale_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='販売価格'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='sale_start',
            field=models.DateTimeField(verbose_name='販売開始日時'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='stock',
            field=models.IntegerField(verbose_name='在庫数'),
        ),
    ]
