# Generated by Django 4.2 on 2023-11-28 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_remove_sale_actual_price_alter_product_product_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='sale_type',
            field=models.CharField(blank=True, choices=[('general_sales', '一般商品'), ('melimit_sales', '共同販売商品')], max_length=20, verbose_name='販売タイプ'),
        ),
    ]
