# Generated by Django 4.2 on 2023-11-29 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_alter_sale_sale_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='is_shipped',
            field=models.BooleanField(default=False, verbose_name='発送状況'),
        ),
    ]
