# Generated by Django 4.2 on 2023-11-29 03:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_sale_is_shipped'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sale',
            name='is_shipped',
        ),
    ]
