# Generated by Django 4.2 on 2023-11-29 06:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_remove_sale_is_shipped'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_price',
            field=models.IntegerField(verbose_name='定価'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='sale_price',
            field=models.IntegerField(verbose_name='販売価格'),
        ),
        migrations.CreateModel(
            name='Threshold',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount_rate', models.IntegerField(verbose_name='割引率')),
                ('threshold', models.IntegerField(verbose_name='しきい値')),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.sale')),
            ],
        ),
    ]
