# Generated by Django 4.2 on 2024-02-06 00:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='address',
            field=models.CharField(max_length=30, verbose_name='住所'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='city',
            field=models.CharField(max_length=30, verbose_name='市区町村'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='phone_number',
            field=models.CharField(max_length=11, validators=[django.core.validators.RegexValidator('^\\d{10,11}$', '10桁または11桁の半角数字を入力してください。')], verbose_name='電話番号'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='postal_code',
            field=models.CharField(max_length=7, validators=[django.core.validators.RegexValidator('^\\d{7}$', '7桁の半角数字を入力してください。')], verbose_name='郵便番号'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='prefecture',
            field=models.CharField(max_length=10, verbose_name='都道府県'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(max_length=20, verbose_name='名前（店舗名）'),
        ),
    ]
