# Generated by Django 4.2 on 2023-11-06 02:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_rename_name_customuser_username'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='melimitstore',
            options={'verbose_name': 'store', 'verbose_name_plural': 'stores'},
        ),
        migrations.AlterModelOptions(
            name='melimituser',
            options={'verbose_name': 'お客さん', 'verbose_name_plural': 'お客さんたち'},
        ),
    ]
