# Generated by Django 4.2 on 2023-11-09 05:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_melimitstore_options_alter_melimituser_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='MelimitStoreDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_image', models.ImageField(blank=True, upload_to='store_image')),
                ('site_url', models.URLField(blank=True, verbose_name='サイトURL')),
            ],
            options={
                'verbose_name': 'store',
                'verbose_name_plural': 'stores',
            },
        ),
        migrations.CreateModel(
            name='MelimitUserDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'お客さんの詳細',
                'verbose_name_plural': 'お客さんたちの詳細',
            },
        ),
        migrations.CreateModel(
            name='UserType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typename', models.CharField(max_length=150, verbose_name='ユーザ種別')),
            ],
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_store',
            field=models.BooleanField(default=False, verbose_name='is_store'),
        ),
        migrations.AlterModelTable(
            name='customuser',
            table='custom_user',
        ),
        migrations.DeleteModel(
            name='MelimitUser',
        ),
        migrations.AddField(
            model_name='melimituserdetail',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='detail_MelimitUser', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='melimitstoredetail',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='detail_MelimitStore', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='customuser',
            name='usertype',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='accounts.usertype', verbose_name='ユーザ種別'),
        ),
    ]
