# Generated by Django 4.2 on 2023-11-09 05:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_melimitstoredetail_melimituserdetail_usertype_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MelimitStore',
        ),
    ]
