# Generated by Django 4.2 on 2023-11-09 06:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_delete_melimitstore'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usertype',
            name='typename',
        ),
        migrations.AddField(
            model_name='usertype',
            name='is_typename',
            field=models.BooleanField(default=False, verbose_name='is_typename'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='usertype',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='accounts.usertype', verbose_name='ユーザ種別'),
        ),
    ]
