# Generated by Django 4.2 on 2023-11-09 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_remove_usertype_typename_usertype_is_typename_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='usertype',
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_typename',
            field=models.BooleanField(default=False, verbose_name='is_typename'),
        ),
        migrations.DeleteModel(
            name='UserType',
        ),
    ]
