# Generated by Django 4.2 on 2023-11-10 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_remove_customuser_usertype_customuser_is_typename_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(blank=True, max_length=30, unique=True, verbose_name='名前（店舗名）'),
        ),
    ]
