# Generated by Django 4.2 on 2023-11-13 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_customuser_is_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(blank=True, choices=[('melimit_user', 'MelimitUser'), ('melimit_store', 'MelimitStore')], max_length=20, null=True),
        ),
    ]
