# Generated by Django 4.2 on 2023-11-15 04:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_customuser_user_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'verbose_name': 'user', 'verbose_name_plural': 'CustomUser'},
        ),
        migrations.AlterModelOptions(
            name='melimitstore',
            options={'verbose_name': 'store', 'verbose_name_plural': 'MelimitStore'},
        ),
        migrations.AlterModelOptions(
            name='melimituser',
            options={'verbose_name': 'お客さん', 'verbose_name_plural': 'MelimitUser'},
        ),
    ]
