# Generated by Django 4.2 on 2023-11-15 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
        ('accounts', '0009_customuser_user_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='melimituser',
            name='ingredients',
            field=models.ManyToManyField(to='user.ingredient'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
