# Generated by Django 4.2 on 2023-11-16 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alter_customuser_options_alter_melimitstore_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(blank=True, max_length=30, unique=True, verbose_name='名前（店舗名）'),
        ),
    ]
