# Generated by Django 4.2 on 2023-11-21 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_alter_customuser_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='melimituser',
            name='taste',
            field=models.CharField(blank=True, choices=[('meat', '肉'), ('vegetables', '野菜'), ('fruit', '果物'), ('fish', '魚')], max_length=20, verbose_name='好み'),
        ),
    ]
