# Generated by Django 4.2 on 2023-11-21 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_alter_melimituser_taste'),
    ]

    operations = [
        migrations.AlterField(
            model_name='melimituser',
            name='taste',
            field=models.CharField(blank=True, choices=[('meat', '肉'), ('vegetables', '野菜'), ('fruit', '果物'), ('fish', '魚')], max_length=20, verbose_name='好み'),
        ),
    ]
