# Generated by Django 4.2 on 2023-11-21 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_alter_melimituser_taste'),
    ]

    operations = [
        migrations.AlterField(
            model_name='melimituser',
            name='taste',
            field=models.CharField(blank=True, choices=[('肉', 'meat'), ('野菜', 'vegetables'), ('果物', 'fruit'), ('魚', 'fish')], max_length=20, verbose_name='好み'),
        ),
    ]
