# Generated by Django 4.2 on 2023-11-21 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_alter_melimituser_taste'),
    ]

    operations = [
        migrations.AlterField(
            model_name='melimituser',
            name='taste',
            field=models.CharField(blank=True, choices=[('meat', 'meat'), ('vegetables', 'vegetables'), ('fruit', 'fruit'), ('fish', 'fish')], max_length=20, verbose_name='好み'),
        ),
    ]
